# Use an official Ubuntu runtime as a parent image
FROM ubuntu:20.04

# Prevent prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update


# Define the command to run the tests
CMD ["tail", "-f", "/dev/null"]
